-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 09:09:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CATEGORIES` ;

CREATE TABLE IF NOT EXISTS `CATEGORIES` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `CATEGORIES` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS` ;

CREATE TABLE IF NOT EXISTS `USERS` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `nickname_UNIQUE` ON `USERS` (`nickname` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POSTS` ;

CREATE TABLE IF NOT EXISTS `POSTS` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `createdAt` DATE NOT NULL,
  `deletedAt` DATE NOT NULL,
  `priority` INT(11) NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `POSTS_ibfk_1`
    FOREIGN KEY (`users_id`)
    REFERENCES `USERS` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `users_id` ON `POSTS` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `COMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `COMS` ;

CREATE TABLE IF NOT EXISTS `COMS` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(150) NOT NULL,
  `createdAt` DATE NOT NULL,
  `users_id` INT(11) UNSIGNED NOT NULL,
  `posts_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `COMS_ibfk_2`
    FOREIGN KEY (`users_id`)
    REFERENCES `USERS` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `COMS_ibfk_3`
    FOREIGN KEY (`posts_id`)
    REFERENCES `POSTS` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `posts_id` ON `COMS` (`posts_id` ASC) VISIBLE;

CREATE INDEX `users_id` ON `COMS` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `POST-CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POST-CATEGORY` ;

CREATE TABLE IF NOT EXISTS `POST-CATEGORY` (
  `posts_id` INT(11) UNSIGNED NOT NULL,
  `categories_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`posts_id`, `categories_id`),
  CONSTRAINT `POST-CATEGORY_ibfk_2`
    FOREIGN KEY (`categories_id`)
    REFERENCES `CATEGORIES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `POST-CATEGORY_ibfk_3`
    FOREIGN KEY (`posts_id`)
    REFERENCES `POSTS` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `posts_id` ON `POST-CATEGORY` (`posts_id` ASC) VISIBLE;

CREATE INDEX `categories_id` ON `POST-CATEGORY` (`categories_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
